import './globals.css'
import { GlobalState } from '@/components/utility/globalState'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-full overflow-y-hidden">
        <GlobalState>
          {children}
        </GlobalState>
      </body>
    </html>
  )
}
